#:schema https://json.schemastore.org/rust-toolchain.json

[toolchain]
channel = "nightly-2025-01-01"
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-docs",
	"rust-src",           # for rust-analyzer
	"rustc",
	"rustfmt",
]
targets = [
	# 64bits Linux Desktop
	"x86_64-unknown-linux-gnu",
]